#!/usr/bin/env python3
import sys
from pathlib import Path
import math
import re

def findCoverRep(baseRep):
    return baseRep.glob("*-trace/**/cover/")

def loadCover(path):
    resTab=[]
    for line in open(path).readlines():
        spline=[x.strip() for x in line.split(":")]
        count=int(spline[0])
        bbRep=spline[1]
        resTab+=[(bbRep, count)]
    return resTab

def countInitTab(line):
    count=0
    for i in range(len(line)):
        if line[i]!='\t':
            return count
        else:
            count+=1
    return count

regExpBack=re.compile("([^\t]+)\t([^\t]*)\:([0-9]+)")
regExpBB_Fcmp=re.compile("([^\t]+) F\?\t([0-9]+)")
regExpBB_F=re.compile("([^\t]+) F\t([0-9]+)")
regExpBB=re.compile("([^\t]+)\t([0-9]+)")

def loadBack(path):
    resTab=[]
    for line in open(path).readlines():
        level=countInitTab(line)
        remain=line[level:]
        if remain.endswith('\n'):
            remain=remain[0:-1]
        backMatch=regExpBack.match(remain)
        BB_FcmpMatch=regExpBB_Fcmp.match(remain)
        BB_FMatch=regExpBB_F.match(remain)
        BB_Match=regExpBB.match(remain)

        if backMatch!=None and (BB_FMatch!=None or BB_FMatch!=None or BB_FcmpMatch!=None):
            print("conflict regexp")
            sys.exit(42)

        if backMatch!=None:
            sym=backMatch.group(1)
            fileName=backMatch.group(2)
            lineNum=backMatch.group(3)
            resTab+=[("back", level, sym, fileName, lineNum)]
            #print("resTab[-1]", resTab[-1])
            continue

        #print("remain", [remain])
        if remain==":0":
            resTab+=[("back", level, "","",0)]
            #print("resTab[-1]", resTab[-1])
            continue
        if BB_FcmpMatch!=None or BB_FMatch!=None or BB_Match!=None:
            BBRep=None
            count=None
            containF=None
            containCMP=None
            if BB_FcmpMatch!=None:
                BBRep=BB_FcmpMatch.group(1)
                count=BB_FcmpMatch.group(2)
                containF=True
                containCMP=True
            if BB_FMatch!=None and containCMP==None:
                BBRep=BB_FMatch.group(1)
                count=BB_FMatch.group(2)
                containF=True
                containCMP=False
            if BB_Match!=None and containF==None:
                BBRep=BB_Match.group(1)
                count=BB_Match.group(2)
                containF=False
                containCMP=False
                print("dhnjuiczsjbhufzejbhzefjbhufzeiuh")
                sys.exit(42)
            resTab+=[("BB", level, BBRep,containF, containCMP, int(count))]
            #print("resTab[-1]", resTab[-1])
            continue
        print("unmatch", [remain])
        sys.exit(42)
    return resTab

def analyseCoverRep(path):
    coverDict={"pathCover":{},
               "dataCover":{},
               "pathBack":{},
               "dataBack":{},
               }
    coverFileTab=path.glob("cover*-seqCount*")
    maxCoverIndex=[]
    maxSeqIndex=-1
    for path in coverFileTab:
        strPath=str(path.name)
        isBack=("coverBack" in strPath)
        coverOrcoverBack="cover"
        if isBack:
            coverOrcoverBack="coverBack"

        coverIndex= int((strPath.split("-")[0]).replace(coverOrcoverBack,""))
        seqIndex  = int((strPath.split("-")[1]).replace("seqCount",""))
        if seqIndex>maxSeqIndex:
            maxSeqIndex=seqIndex
            maxCoverIndex+= ([-1]*(seqIndex-maxSeqIndex+1))
        if coverIndex>maxCoverIndex[seqIndex]:
            maxCoverIndex[seqIndex]=coverIndex
        if isBack:
            coverDict["pathBack"][(coverIndex, seqIndex)]=path
        else:
            coverDict["pathCover"][(coverIndex, seqIndex)]=path
    coverDict["nbSeq"]=maxSeqIndex+1
    coverDict["nbCoverTab"]=[x+1 for x in maxCoverIndex]
    for seq in range(coverDict["nbSeq"]):
        for cov in range(coverDict["nbCoverTab"][seq]):
            if not (cov,seq) in coverDict["pathCover"].keys():
                print("cov/seq", cov, seq)
                print("data", coverDict["pathCover"].keys())
                print("data missing")
                sys.exit(42)
            if not (cov,seq) in coverDict["pathBack"].keys() and coverDict["pathBack"]!={}:
                print("cov/seq", cov, seq)
                print("data", coverDict["pathBack"].keys())
                print("data missing")
                sys.exit(42)

            coverDict["dataCover"][(cov, seq)]=loadCover(coverDict["pathCover"][(cov, seq)])
            if coverDict["pathBack"]!={}:
                coverDict["dataBack"][(cov, seq)]=loadBack(coverDict["pathBack"][(cov, seq)])
    #print(coverDict)
    return coverDict

def analysePath(baseRep, path):
    relativePathStr=str(path.relative_to(baseRep))
    print("relativePathStr", relativePathStr)
    dataStr=relativePathStr.split("/")
    conf_name=dataStr[0].replace("-trace","")
    rounding=dataStr[1]
    indexNext=2
    if dataStr[1]=="det":
        rounding=dataStr[2]
        indexNext=3
    ddRunIndex=int( dataStr[indexNext].replace("dd.run",""))

    returnPath=path / ".." / "dd.return.value"
    returnValue=int(open(returnPath).readline())
    returnStr="OK"
    if returnValue!=0:
        returnStr="KO"
    computationData={"path":path,
                     "runIndex":ddRunIndex,
                     "rounding": rounding,
                     "conf_name": conf_name,
                     "return_value": returnStr,
                     "cover":analyseCoverRep(path)
                     };
    return computationData

def keyConf(conf):
    if conf=="NoPerturbation":
        return 0
    if conf=="FullPerturbation":
        return 1
    if conf=="rddmin-cmp":
        return 2
    if conf.startswith("ddmin"):
        return 10+ int( conf.replace("ddmin","")) # 10 we keep margin

def keyRounding(rounding):
    tab=["default", "nearest", "downward", "upward", "random", "nearness", "sr_monotonic", "sr_smonotonic"]
    if rounding in tab:
        return tab.index(rounding)
    return len(tab)



def sortDataParsed(computationDataTab):
    return sorted(computationDataTab,key=lambda x: (keyConf(x["conf_name"]), keyRounding(x["rounding"]), x["runIndex"]))


def getRefIndex(dataParsedTab):
    for index in range(len(dataParsedTab)):
        if dataParsedTab[index]["conf_name"]=="NoPerturbation":
            return index
    return 0

def getNewBBStrIndexMultipleBB(mergeData, bbStr):
    lastIndex=-1;
    for data in mergeData:
        if bbStr==data["bbStr"]:
            lastIndex=max(lastIndex,data["index-multipleBB"])
    return lastIndex+1

def getNewBackStrIndexMultipleBB(currentDataTab, tupleData):
    lastIndex=-1;
    for currentData in currentDataTab:
        if all( [currentData["tupleData"][0:-1] == tupleData[0][0:-1], #count is removed
                 currentData["backtrace"] == tupleData[1]]):
            lastIndex=max(lastIndex,currentData["index-multipleBB"])
    return lastIndex


def mergeDataForOnePartialCover(dataParsedTab, seqIndex, covIndex):
    refIndex=getRefIndex(dataParsedTab)

    mergeData=[]

    dataRef=dataParsedTab[refIndex]["cover"]["dataCover"][(covIndex, seqIndex)]
    for bbStr,cover in dataRef:
        dictData={"bbStr":bbStr,
                  "index-multipleBB": getNewBBStrIndexMultipleBB(mergeData,bbStr),
                  "covTab": [None for i in range(len(dataParsedTab)) ]
                  }
        dictData["covTab"][refIndex]=cover
        mergeData.append(dictData)

    for currentIndex in range(len(dataParsedTab)):
        if currentIndex== refIndex:
            continue
        dataCurrent=dataParsedTab[currentIndex]["cover"]["dataCover"][(covIndex, seqIndex)]
        mergeCurrent=[]
        for bbStr,cover in dataCurrent:
            dictData={"bbStr":bbStr,
                      "index-multipleBB": getNewBBStrIndexMultipleBB(mergeCurrent,bbStr),
                      "cov": cover
                      }
            mergeCurrent.append(dictData)

        for dicData in mergeCurrent:
            bbStr=dicData["bbStr"]
            index_multipleBB=dicData["index-multipleBB"]
            cov=dicData["cov"]

            isMerged=False
            for mergeItem in mergeData:
                if mergeItem["bbStr"]==bbStr and mergeItem["index-multipleBB"]==index_multipleBB:
                    mergeItem["covTab"][currentIndex]=cov
                    isMerged=True
                    break
            if isMerged:
                continue
            tabCov=[None for i in range(len(dataParsedTab)) ]
            tabCov[currentIndex]=cov
            mergeData.append( {"bbStr": bbStr , "index-multipleBB":index_multipleBB, "covTab":tabCov})
    return mergeData



def lineTabToMergeTab(lineTab, isRef=True, numberOfSample=0, indexCurrent=0):
    backtrace=[]
    mergeData=[]
    for tupleData in lineTab:
        #resTab+=[("back", level, sym, fileName, lineNum)]
        if tupleData[0]=="back":
            level=tupleData[1]
            if level==len(backtrace):
                backtrace+=[tupleData]
            elif level<len(backtrace):
                backtrace=backtrace[0:level+1]
                backtrace[level]=tupleData
            else:
                print("bogue backtrace?")
                print("lineTab",lineTab)
                print("backtrace", backtrace)
                print("tupleData",tupleData)
                sys.exit()

        #resTab+=[("BB", level, BBRep,containF, containCMP, int(count))]
        if tupleData[0]=="BB":
            level=tupleData[1]
            backtrace=backtrace[0:level]

        dictData={"tupleData":tupleData,
                  "backtrace":backtrace,
                  "index-multipleBB": getNewBackStrIndexMultipleBB(mergeData,(tupleData,backtrace)),
                  }
        #if isRef:
        dictData["backTab"]= [None for i in range(numberOfSample) ]

        if tupleData[0]=="BB":
            countData=tupleData[5]
            dictData["backTab"][indexCurrent]=countData
        mergeData.append(dictData)
    return mergeData

def mergeDataForOnePartialBack(dataParsedTab, seqIndex, covIndex):
    refIndex=getRefIndex(dataParsedTab)
    mergeData=[]
    dataRef=dataParsedTab[refIndex]["cover"]["dataBack"][(covIndex, seqIndex)]

    mergeData=lineTabToMergeTab(dataRef, True, len(dataParsedTab), refIndex)

    for currentIndex in range(len(dataParsedTab)):
        if currentIndex== refIndex:
            continue
        dataCurrent=dataParsedTab[currentIndex]["cover"]["dataBack"][(covIndex, seqIndex)]
        mergeCurrent=lineTabToMergeTab(dataCurrent, False,  len(dataParsedTab), currentIndex)

        for dicData in mergeCurrent:
            tupleData=dicData["tupleData"]
            backtrace=dicData["backtrace"]
            index_multipleBB=dicData["index-multipleBB"]
            count=None
            if tupleData[0]=="BB":
                count=tupleData[5]

            isMerged=False
            for mergeItem in mergeData:
                if mergeItem["tupleData"][0:-1]==tupleData[0:-1] and mergeItem["backtrace"]==backtrace and mergeItem["index-multipleBB"]==index_multipleBB:
                    mergeItem["backTab"][currentIndex]=count
                    isMerged=True
                    break
            if isMerged:
                continue
            backTab=[None for i in range(len(dataParsedTab)) ]
            backTab[currentIndex]=count
            #mergeData.append( {"bbStr": bbStr , "index-multipleBB":index_multipleBB, "covTab":tabCov})
            print("insertion not obvious to code: ignored: ", tupleData)

    return mergeData



def mergeData(dataParsedTab, mergeBack=False):
    nbSeqRef=dataParsedTab[0]["cover"]["nbSeq"]
    nbCoverTabRef=dataParsedTab[0]["cover"]["nbCoverTab"]
    for dataParsed in dataParsedTab:
        nbSeq=dataParsed["cover"]["nbSeq"]
        nbCoverTab=dataParsed["cover"]["nbCoverTab"]
        if nbSeq!=nbSeqRef  or nbCoverTab!=nbCoverTabRef:
            print("incoherent data")
            sys.exit(42)
    mergedDataRes=[[None for cov in range(nbCoverTabRef[seq])] for seq in range(nbSeqRef) ]
    for seqIndex in range(nbSeqRef):
        for covIndex in range(nbCoverTabRef[seqIndex]):
            if mergeBack:
                mergedDataRes[seqIndex][covIndex]=mergeDataForOnePartialBack(dataParsedTab, seqIndex, covIndex)
            else:
                mergedDataRes[seqIndex][covIndex]=mergeDataForOnePartialCover(dataParsedTab, seqIndex, covIndex)
    return mergedDataRes


def computeBBEstimator( tabCount, tabStatus, refIndex, estimatorTab):
    countRef=tabCount[refIndex]
    statusRef=tabStatus[refIndex]
    assert(statusRef=="OK")

    equalOK, diffOK, equalKO, diffKO=(0,0,0,0)
    for index in range(len(tabCount)):
        isEqual= (tabCount[index]==countRef)
        isOK= (tabStatus[index]=="OK")

        if isEqual and isOK: equalOK+=1
        if isEqual and (not isOK): equalKO+=1
        if (not isEqual) and isOK: diffOK+=1
        if (not isEqual) and (not isOK): diffKO+=1

    #https://arxiv.org/pdf/1306.4546
    n11,n10,n01,n00  = diffKO,diffOK,equalKO,equalOK #notation for ochiai and tarantual

    res={}
    for estimatorStr in estimatorTab:
        estim=None
        if estimatorStr=="biased":
            estim= 0.5* (float(diffKO)/ float(diffKO+equalKO) + float(equalOK)/float(equalOK+diffOK))
        if estimatorStr=="standard":
            estim= float(diffKO + equalOK)/ float(equalOK + equalKO+ diffOK+diffKO)
        if estimatorStr=="ochiai":
            estim=n11 / math.sqrt( (n11+ n01) * (n11+ n10 ) )
        if estimatorStr=="tarantula":
            estim= (n11/ (n11+n01)) / ((n11 / (n11+n01)) + (n10 / (n10+n00)))
        res[estimatorStr]=estim

    return res


def updateEstimator(mergedData,dataParsedTab,estimatorTab=["standard","biased","ochiai", "tarantula"], backVersion=False):
    nbSeqRef=dataParsedTab[0]["cover"]["nbSeq"]
    nbCoverTabRef=dataParsedTab[0]["cover"]["nbCoverTab"]
    refIndex=getRefIndex(dataParsedTab)
    keyTab="covTab"
    if backVersion:
        keyTab="backTab"

    for seqIndex in range(nbSeqRef):
        for covIndex in range(nbCoverTabRef[seqIndex]):
            for indexBB in range(len(mergedData[seqIndex][covIndex])):
                bbDict=mergedData[seqIndex][covIndex][indexBB]

                bbDict["estimator"]=computeBBEstimator(bbDict[keyTab],
                                                       [x["return_value"] for x in dataParsedTab],
                                                       refIndex,
                                                       estimatorTab)


def dumpCSVdata( mergeData, dataParsedTab, estimatorTab, output=".", backVersion=False):
    nbSeqRef=dataParsedTab[0]["cover"]["nbSeq"]
    nbCoverTabRef=dataParsedTab[0]["cover"]["nbCoverTab"]

    for seqIndex in range(nbSeqRef):
        for covIndex in range(nbCoverTabRef[seqIndex]):
            name="coverage"
            if backVersion:
                name="backCover"
            outPutHandler=open(str(output)+ "/"+name+"Data_seq%i_cover%i.csv"%(seqIndex, covIndex),"w")
            #header
            levelPrefix=""
            if backVersion:
                levelPrefix="\t"

            outPutHandler.write(levelPrefix+"" +"\t" + "\t".join(estimatorTab)+"\n")
            outPutHandler.write(levelPrefix+"conf_name" +"\t" + "\t".join([""]*len(estimatorTab))+ "\t"+"\t".join([str(x["conf_name"]) for x in dataParsedTab]) +"\n" )
            outPutHandler.write(levelPrefix+"indexRun" +"\t" + "\t".join([""]*len(estimatorTab))+ "\t"+ "\t".join([str(x["runIndex"]) for x in dataParsedTab])  +"\n")
            outPutHandler.write(levelPrefix+"rounding" +"\t" + "\t".join([""]*len(estimatorTab))+ "\t"+"\t".join([str(x["rounding"]) for x in dataParsedTab])  +"\n")
            outPutHandler.write(levelPrefix+"return_value" +"\t" +"\t".join([""]*len(estimatorTab))+ "\t"+ "\t".join([str(x["return_value"]) for x in dataParsedTab])  +"\n")

            #data
            mergeDataSeqCov=mergeData[seqIndex][covIndex]
            if backVersion:
                print("mergeDataSeqCov",mergeDataSeqCov)
                for backLine in mergeDataSeqCov:
                    if backLine["tupleData"][0]=="BB":
                        level=backLine["tupleData"][1]
                        BBName=backLine["tupleData"][2]

                        outPutHandler.write(str(level)+"\t"+BBName +"\t"+ "\t".join([str(backLine["estimator"][key]) for key in estimatorTab])+"\t"  + "\t".join([str(x) for x in  backLine["backTab"]])+"\n")
                    if backLine["tupleData"][0]=="back":
                        level=backLine["tupleData"][1]
                        sym=backLine["tupleData"][2]
                        fileName=backLine["tupleData"][3]
                        lineNum=backLine["tupleData"][4]
                        name=sym+" "+fileName+":"+str(lineNum)

                        outPutHandler.write("|"+str(level)+"\t"+name +"\t"+ "\t".join(["" for key in estimatorTab])+"\t"  + "\t".join(["" for x in  backLine["backTab"]])+"\n")

            else:
                for bb in mergeDataSeqCov:
                    outPutHandler.write(bb["bbStr"] +"\t"+ "\t".join([str(bb["estimator"][key]) for key in estimatorTab])+"\t"  + "\t".join([str(x) for x in  bb["covTab"]])+"\n")
            outPutHandler.close()


if __name__=="__main__":
    baseRep=Path(".")
    if len(sys.argv)==2:
        baseRep=Path(sys.argv[1])

    pathTab=list(findCoverRep(baseRep))
    if len(pathTab)==0:
        print("invalid baseRep:" , baseRep)
        sys.exit(42)

    dataParsed=[analysePath(baseRep,path) for path in pathTab]
    dataParsed=sortDataParsed(dataParsed)

    estimatorTab=["standard","biased"] #, "ochiai","tarantula"]
    backVersion=True
    dataMerged=mergeData(dataParsed,backVersion)
    updateEstimator(dataMerged, dataParsed, estimatorTab, backVersion=backVersion)

#    print(dataMerged)
    dumpCSVdata(dataMerged , dataParsed, estimatorTab, backVersion=backVersion)
