#!/usr/bin/env python3

from traceAnalysis import generateTraceAnalysis
from pathlib import Path
import sys

if __name__=="__main__":
    baseRep=Path(".")
    if len(sys.argv)==2:
        baseRep=Path(sys.argv[1])

    trace_kind="back"
    trace_kind="bb"
    estimatorTab=["standard","biased","biased-stol","fdr-stol", "data"]
    clean=False

    generateTraceAnalysis(baseRep, trace_kind, estimatorTab, clean)
