#!/usr/bin/env python3
# Copyright (C) 2014-2021 EDF
#   B. Lathuilière <bruno.lathuiliere@edf.fr>


# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public License as
# published by the Free Software Foundation; either version 3 of the
# License, or (at your option) any later version.

# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.

# You should have received a copy of the GNU Lesser General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
# 02111-1307, USA.

# The GNU Lesser General Public License is contained in the file COPYING.


from BBTools import cmpToolsCov, traceName
import sys
import getopt
from pathlib import Path

def extractPidRep(fileName, trace_kind="bb"):
    """extract the pid d'un fichier de la form trace_bb_cov.log-PID[.gz]"""
    rep=fileName.parent
    if rep=="":
        rep="."
    baseFile=fileName.name
    begin=traceName(trace_kind).covPrefixName()

    mtime=(fileName.stat()).st_mtime
    if baseFile.startswith(begin):
        pid=int((baseFile.replace(begin,'')).replace(".gz",""))
        return (pid,rep,mtime)
    return None

def selectPidFromFile(fileNameTab, trace_kind="bb"):
    """Return a list of pid from a list of file by using extractPidRep"""
    return [extractPidRep(fileName,trace_kind)[0:2] for fileName in fileNameTab]

def selectSortedPidFromFile(fileNameTab,trace_kind="bb"):
    """Return a list of pid from a list of file by using extractPidRep"""
    pidList=[extractPidRep(fileName,trace_kind) for fileName in fileNameTab]
    sortedPidList=sorted(pidList, key=lambda x: x[2])
    return [x[0:2] for x in sortedPidList ]


class config_option:
    def __init__(self,argv):
        #default Value
        self.genCov=False
        self.genCovBack=False
        self.genCovCorrelation=False
        self.select_default=None
        self.run_cmp=None
        self.run_eval=None
        self.argv=argv
        self.pidRename=None
        self.trace_kind="back"
        #parse Argv
        self.parseOpt(argv[1:])

    def usage(self):
        print ("Usage: %s [--help] [--genCov] [--genCovBack] [--genCovCorrelation] [--select-default[=INT]] [--run-cmp=] [--pidRename] file list of type trace_bb_cov.log* "%(self.argv[0]) )
        sys.exit(42)

    def parseOpt(self,argv):
        try:
            opts,args=getopt.getopt(argv, "h",["help","genCov","genCovBack","genCovCorrelation", "pidRename", "select-default=","run-cmp=", "run-eval="])
        except getopt.GetoptError:
            self.usage()

        for opt, arg in opts:
            if opt in ["-h", "--help"]:
                self.usage()
                sys.exit()
            if opt in ["--genCov"]:
                self.genCov=True
            if opt in ["--genCovBack"]:
                self.genCovBack=True
            if opt in ["--pidRename"]:
                self.pidRename=True
            if opt in ["--genCovCorrelation"]:
                self.genCovCorrelation=True
            if opt in ["--run-cmp"]:
                self.run_cmp=arg
            if opt in ["--run-eval"]:
                self.run_eval=arg
            if opt in ["--select-default"]:
                if arg=="0":
                    self.select_default=True
                else:
                    self.select_default=int(arg)

        #default configuartion : genCov
        if not (self.genCovCorrelation or self.genCov):
            self.genCov=True
        if self.run_eval!=None and self.run_cmp!=None:
            print("--run-cmp= and --run-eval= are incompatible option")
            self.usage()

        self.listOfFiles=self.search_default_param()

        listArgToAdd=[]
        for arg in args:
            if arg not in self.listOfFiles:
                listArgToAdd+=[arg]
        self.listOfFiles=listArgToAdd +self.listOfFiles

        if len(self.listOfFiles)<1 and self.genCov:
            print("--genCov required at least 1 argument")
            self.usage()
        if len(self.listOfFiles)<2 and self.genCovCorrelation:
            print("--genCovCorrelation required at least 2 arguments")
            self.usage()
        self.listOfFiles=[Path(x) for x in self.listOfFiles]

    def search_default_param(self):
        import pathlib
        addFile=[str(x) for x in pathlib.Path(".").rglob(traceName(self.trace_kind).covPrefixName() +"*")]
        if self.select_default==True:
            return addFile
        if isinstance(self.select_default,int):
            return addFile[0:self.select_default]
        return []


if __name__=="__main__":
    options=config_option(sys.argv)
    pidList=None
    pidMap=None

    if options.pidRename==None:
        pidList=selectPidFromFile(options.listOfFiles, options.trace_kind)
    else:
        pidList=selectSortedPidFromFile(options.listOfFiles, options.trace_kind)
        rank=0
        pidMap={}
        for pidRepTuple in pidList:
            pid=pidRepTuple[0]
            rep=pidRepTuple[1]
            pidMap[pid]="rank"+str(rank)
            rank+=1

    cmp=cmpToolsCov(pidList, options.run_cmp, options.run_eval, options.trace_kind)
    if options.genCov:
        if options.pidRename:
            cmp.writePartialCover(pidMap=pidMap)
        else:
            cmp.writePartialCover()

    if options.genCovBack:
        if options.pidRename:
            cmp.writePartialBack(pidMap=pidMap)
        else:
            cmp.writePartialBack()

    if options.genCovCorrelation:
        cmp.findRefForMerge()
        cmp.writeMergedCov("biased")
#        cmp.writeMergedCov("standard")
