#!/usr/bin/env python3
import os
import sys
import re
import fnmatch
import glob
import functools
import copy
import DD_stoch
import post_config
import rounding_tool
from pathlib import Path

from BBTools import traceName
from traceAnalysis import  generateTraceAnalysis

def failure():
    sys.exit(42)


def genDefaultTraceFile(config, refDir, binary=True ,listOfExpr=[]):
    res=[]
    for fileSym in refDir.glob("dd.sym.*"):
        for line in open(fileSym):
            objectVerrou=(line.strip()).split("\t")[1]
            if binary and (".so" not in objectVerrou and objectVerrou not in res):
                res+=[objectVerrou]
                continue
            for expr in listOfExpr:
                if fnmatch.fnmatch(objectVerrou, expr) and objectVerrou not in res:
                    res+=[objectVerrou]
                    break
    if len(res)==0:
        print("defaultTrace is empty")
        failure()

    outputFileName=refDir / "defaultTrace"
    output=open(outputFileName,"w")
    for objectVerrou in res:
        output.write("*\t"+objectVerrou+"\n")
    output.close()
    return outputFileName



def getSortedPidList(config, rep):
    tName=traceName(config.get_trace_type())
    pidList=[(int((x.name).replace(tName.covPrefixName(),"")), x.stat().st_mtime)
             for x in  rep.glob(tName.covPrefixName()+"*") if x.name != (tName.covPrefixName()+"seqCount") ]
    sortedPidList=sorted(pidList, key=lambda x: x[1])
    return sortedPidList


def mapClean(rep, listOfFile, verbose):
    for fileName in listOfFile:
        pathName= rep / fileName
        if verbose:
            print("delete : ", pathName)
        pathName.unlink()

def mapCompress(rep, listOfFile, verbose):
    for fileName in listOfFile:
        pathName= rep / fileName
        cmd="gzip %s"%(str(pathName))
        if verbose:
            print("compress cmd : ", cmd)
        os.system(cmd)


def mapRename(rep, pid, count, listOfFile, compress,verbose):
    convList=[(x, x.replace(str(pid), "seqCount"+str(count))) for x in listOfFile]
    for (old,new) in convList:
        oldPath=rep / old
        newPath=rep / new
        if newPath.is_file():
            print("Problem with ", oldPath,newPath)

        if verbose:
            print(oldPath , " => " , newPath)
        oldPath.rename(newPath)
        if compress:
            cmd="gzip %s"%(str(newPath))
            if verbose:
                print("compress cmd : ", cmd)
            os.system(cmd)


def rename_pid_for_one_rep(config, rep, ignoreEmpty=True,verbose=False):
    tName=traceName(config.get_trace_type())
    trace_kind=config.get_trace_type()

    pidList=getSortedPidList(config,rep)
    count=0
    convList=[]
    for pidTuple in pidList:
        pid=pidTuple[0]
        bbOldFileList=[x.name for x in rep.glob("coverBB*-"+str(pid))]
        backOldFileList=[x.name for x in rep.glob("coverBack*-"+str(pid))]
        otherOldFileList=[x.name for x in list(rep.glob("*-"+str(pid)))]
        otherOldFileList=[x for x in otherOldFileList if not x in bbOldFileList+backOldFileList]

        if ignoreEmpty:
            fileName=tName.bbName(pid)
            pathFile=rep / fileName
            if  fileName in  otherOldFileList and (pathFile.stat()).st_size==0:
                mapClean(rep,otherOldFileList+bbOldFileList+backOldFileList, verbose)

        if trace_kind=="bb_cover":
            mapRename(rep,pid,count, bbOldFileList, config.get_trace_compress(),verbose)
            mapCompress(rep,otherOldFileList+backOldFileList,verbose)

        if  trace_kind=="back_cover":
            mapRename(rep,pid,count, backOldFileList, config.get_trace_compress(),verbose)
            mapCompress(rep,otherOldFileList+bbOldFileList,verbose)
        count+=1


def parseLastCmd(rep, instr_prefix="VERROU"):
    # maybe we should use a non-human cleaner format
    # parse the result of confToStr defined in gen_config.py
    fileName=rep/ "cmd.last"
    if not fileName.is_file():
        print(fileName, "missing")
        return None
    res={}
    handler=open(fileName,"r")
    line=handler.readline()
    cmd=line.replace("ENV ","").replace(":\n","")
    res["cmd"]=cmd
    res["env"]={}
    line=handler.readline()
    while line!= "ENV "+instr_prefix+":\n":
        if line.startswith("\tPWD="):
            res["env"]["PWD"]=line.replace("\tPWD=","").strip()
        line=handler.readline()
    line=handler.readline()
    while not line.startswith("Cmd:"):
        if line.startswith("\t"+instr_prefix+"_"):
            spline=line.strip().split("=",1)
            res["env"][spline[0]]=spline[1]
        else:
            print("Parsing error", fileName)
            print("line", line)
            return None
        line=handler.readline()
    return res


class trace_handler:

    def __init__(self, config):
        self.config=config
        self.tName=traceName(config.get_trace_type())

    def postRunTrace(self,runDir):
        globListOfTraceBBFile=runDir.glob("cover/"+self.tName.covPrefixName()+"*")

        listOfTraceBBFile=[]
        log=""
        for traceBBFile in globListOfTraceBBFile:
            traceInfo=traceBBFile.with_name( self.tName.bbNameForCovName(traceBBFile.name))
            if (traceInfo.stat()).st_size!=0:
                listOfTraceBBFile+=[traceBBFile]
            else:
                log+="traceBBFile %s ignored\n"%(traceBBFile)
        if log!="":
            with open(runDir / "gen_trace_log", "w") as f:
                f.write(log)

        if len(listOfTraceBBFile)==0:
            print("Problem in trace generation detected: ",runDir)
            sys.exit(42)

        if self.config.get_trace_gen_local():
            option="--pidRename --trace-type=%s --output-type=individual"%(config.get_trace_type())

            cmd="verrou_gen_trace "+option+" %s"%(" ".join([str(x) for x in listOfTraceBBFile]))
            #print("cmd: ", cmd)
            os.system(cmd+ "  >> %s"%( runDir/ "gen_trace_log"))

        rename_pid_for_one_rep(self.config, runDir / "cover", ignoreEmpty=True)

    def preRunTrace(self, runDir, env):
        coverRep=runDir / "cover"
        coverRep.mkdir()
        env["VERROU_OUTPUT_TRACE_REP"]=coverRep

def runOneConfig(config, refDir, outputDir, envvars, nbRun, traceFile=None):
    runScript=config.get_runScript()
    cmpScript=config.get_cmpScript()

    seedTab=None
    seed=config.getSeed()
    if seed!=None:
        import random
        random.seed(seed)
        seedTab=random.sample(range(0,2**32-1), config.get_nbRUN())

    if traceFile!=None:
        envvars["VERROU_TRACE"]=traceFile
        envvars["VERROU_TRACE_TYPE"]=config.get_trace_type()

    task=DD_stoch.stochTask(outputDir, refDir,runScript, cmpScript, envvars , seedTab=seedTab, seedEnvVar="VERROU_SEED")
    task.setNbRun(nbRun)
    if config.get_trace():
        traceTool=trace_handler(config)
        task.setPreRun(traceTool.preRunTrace)
        task.setPostRun(traceTool.postRunTrace)

    DD_stoch.runMultipleStochTask([task],config.get_maxNbPROC())


def mergeIOmatchScript(config, mainIOMatchFile, destRep):
    destFile=str(destRep) + "/merged_IOMatch.txt"
    destHandler=open(destFile, "w")
    headerIOMatchLines=config.get_ioMatchHeader()

    if mainIOMatchFile==None:
        destHandler.write(headerIOMatch)
        return destFile
    isHeaderWritten=False
    for line in open(mainIOMatchFile,"r").readlines():
        if line.startswith("verbose:"):
            destHandler.write("verbose: "+str(config.getIoMatchVerbose())+"\n")
            continue
        if line.startswith("bmatch:") or line.startswith("cmatch:"):
            if not isHeaderWritten:
                destHandler.write(headerIOMatchLines+"\n")
            destHandler.write(line)
            isHeaderWritten=True
            continue
        if line.startswith("nb-match-max:"):
            value=int(line.split(":")[1])+config.get_ioMatchHeaderShift()
            destHandler.write("nb-match-max: "+str(value)+"\n")
            continue
        if line.startswith("permutable-bmatch-indexes:"):
            valueTab=line.split()[1:3]
            value1,value2=[int(x)+ config.get_ioMatchHeaderShift() for x in valueTab]
            destHandler.write("permutable-bmatch-indexes: "+ str(value1)+ " "+str(value2)+"\n")
            continue
        destHandler.write(line)
    if not isHeaderWritten:
        destHandler.write(headerIOMatchLines+"\n")

    destHandler.close()
    return destFile

def failEnvBacktrace():
    print("post_verrou_dd do not accept the use of VERROU_EXCLUDE_BACKTRACE")
    failure()

def buildRunEnv(config,parsedCmd,ddmin, instr, ddminNew):
    runEnv={}

    if ddmin.name != "ref":
        if "verrou_dd_sym" in parsedCmd["cmd"]:
            if "VERROU_EXCLUDE" in parsedCmd["env"]:
                print("Warning VERROU_EXCLUDE overwritten")
            if "VERROU_SOURCE" in parsedCmd["env"]:
                runEnv["VERROU_SOURCE"]=Path(parsedCmd["env"]["PWD"]) / parsedCmd["env"]["VERROU_SOURCE"]
            if "VERROU_IOMATCH_CLR" in parsedCmd["env"]:
                runEnv["VERROU_IOMATCH_CLR"]= mergeIOmatchScript(config, Path(parsedCmd["env"]["PWD"]) / parsedCmd["env"]["VERROU_IOMATCH_CLR"], ddminNew)
                runEnv["VERROU_OUTPUT_IOMATCH_REP"]= "%DDRUNABS%"
            if "VERROU_EXCLUDE_BACKTRACE" in parsedCmd["env"]:
                failEnvBacktrace()
                runEnv["VERROU_BACKTRACE"]=Path(parsedCmd["env"]["PWD"]) / parsedCmd["env"]["VERROU_EXCLUDE_BACKTRACE"]
            runEnv["VERROU_EXCLUDE"]=ddmin / "dd.sym.exclude"

        elif "verrou_dd_line" in parsedCmd["cmd"]:
            if "VERROU_SOURCE" in parsedCmd["env"]:
               print("Warning VERROU_SOURCE overwritten")
            if "VERROU_WARN_UNKNOWN_SOURCE"  in parsedCmd["env"]:
               print("Warning VERROU_WARN_UNKNOWN_SOURCE overwritten")
            if "VERROU_EXCLUDE" in parsedCmd["env"]:
                runEnv["VERROU_EXCLUDE"]==Path(parsedCmd["env"]["PWD"]) / parsedCmd["env"]["VERROU_EXCLUDE"]
            if "VERROU_IOMATCH_CLR" in parsedCmd["env"]:
                runEnv["VERROU_IOMATCH_CLR"]= mergeIOmatchScript(config, Path(parsedCmd["env"]["PWD"]) / parsedCmd["env"]["VERROU_IOMATCH_CLR"], ddminNew)
                runEnv["VERROU_OUTPUT_IOMATCH_REP"]= "%DDRUNABS%"
            if "VERROU_EXCLUDE_BACKTRACE" in parsedCmd["env"]:
                failEnvBacktrace()
                runEnv["VERROU_BACKTRACE"]=Path(parsedCmd["env"]["PWD"]) / parsedCmd["env"]["VERROU_EXCLUDE_BACKTRACE"]
            runEnv["VERROU_SOURCE"]=ddmin / "dd.line.include"
            runEnv["VERROU_WARN_UNKNOWN_SOURCE"]= ddmin / "dd.line.exclude"

        elif "verrou_dd_back" in parsedCmd["cmd"]:
            print("post_verrou_dd not yet stable for verrou_dd_back : deactivated")
            failure()

            if "VERROU_EXCLUDE_BACKTRACE" in parsedCmd["env"]:
               print("Warning VERROU_EXCLUDE_BACKTRACE overwritten")
            if "VERROU_SOURCE" in parsedCmd["env"]:
                runEnv["VERROU_SOURCE"]=Path(parsedCmd["env"]["PWD"]) / parsedCmd["env"]["VERROU_SOURCE"]
            if "VERROU_EXCLUDE" in parsedCmd["env"]:
                runEnv["VERROU_EXCLUDE"]==Path(parsedCmd["env"]["PWD"]) / parsedCmd["env"]["VERROU_EXCLUDE"]
            if "VERROU_IOMATCH_CLR" in parsedCmd["env"]:
                runEnv["VERROU_IOMATCH_CLR"]= mergeIOmatchScript(config, Path(parsedCmd["env"]["PWD"]) / parsedCmd["env"]["VERROU_IOMATCH_CLR"], ddminNew)
                runEnv["VERROU_OUTPUT_IOMATCH_REP"]= "%DDRUNABS%"
            runEnv["VERROU_EXCLUDE_BACKTRACE"] = ddmin / "dd.back.exclude"


        elif "verrou_dd_stdout" in parsedCmd["cmd"]:
            if "VERROU_IOMATCH_CLR" in parsedCmd["env"]:
                print("Warning VERROU_IOMATCH_CLR overwritten")
            if "VERROU_OUTPUT_IOMATCH_REP" in parsedCmd["env"]:
                print("Warning VERROU_OUTPUT_IOMATCH_REP overwritten")
            if "VERROU_SOURCE" in parsedCmd["env"]:
                runEnv["VERROU_SOURCE"]=Path(parsedCmd["env"]["PWD"]) / parsedCmd["env"]["VERROU_SOURCE"]
            if "VERROU_EXCLUDE" in parsedCmd["env"]:
                runEnv["VERROU_EXCLUDE"]==Path(parsedCmd["env"]["PWD"]) / parsedCmd["env"]["VERROU_EXCLUDE"]
            if "VERROU_EXCLUDE_BACKTRACE" in parsedCmd["env"]:
                failEnvBacktrace()
                runEnv["VERROU_EXCLUDE_BACKTRACE"]==Path(parsedCmd["env"]["PWD"]) / parsedCmd["env"]["VERROU_BACKTRACE"]

            runEnv["VERROU_IOMATCH_CLR"]= mergeIOmatchScript(config, ddmin / "vr_iomatch.txt" , ddminNew)
            runEnv["VERROU_OUTPUT_IOMATCH_REP"]= "%DDRUNABS%"

        else:
            print("post_verrou_dd works only with verrou_dd_sym,verrou_dd_line, verrou_dd_back and verrou_dd_stdout")
            failure()

    if instr!="":
        runEnv["VERROU_INSTR"]= instr
        if "VERROU_INSTR" in parsedCmd["env"]:
            print("Warning VERROU_INSTR  overwritten")
    else:
        if "VERROU_INSTR" in parsedCmd["env"]:
            runEnv["VERROU_INSTR"]=parsedCmd["env"]["VERROU_INSTR"]

    for i in parsedCmd["env"]:
        if i in ["VERROU_INSTR", "VERROU_SOURCE", "VERROU_EXCLUDE", "VERROU_INSTR", "VERROU_EXCLUDE_BACKTRACE", "VERROU_IOMATCH_CLR","VERROU_OUTPUT_IOMATCH_REP"]:
            continue # treated above
        if i in ["PWD"]:
            continue
        if i.startswith("VERROU_COMPILED_WITH_"):
            continue
        print("Forward env ", i, "=" , parsedCmd["env"][i])
        runEnv[i]=parsedCmd["env"][i]

    return runEnv

def runSubRepForOneInstr( config, rep, refDir,ddMinList):

    instrList=config.get_instr()

    refNewDir=refDir
    traceFile=None
    if config.get_trace():
        traceFile=config.get_trace_file()
        if traceFile==None:
            traceFile=genDefaultTraceFile(config, refDir,
                                          config.get_trace_bin(),
                                          config.get_trace_pattern())
        refNewDir=refNewDir.with_name( refNewDir.name+"-trace")

    parsedCmd=parseLastCmd(rep)

    for ddmin in ddMinList:

        ddminNew=ddmin
        if config.get_trace():
            ddminNew=ddminNew.with_name( ddminNew.name+"-trace")

        for instr in instrList:
            ddminNewInstr=ddminNew.with_name( ddminNew.name+"-"+instr)
            if instr=="":
                ddminNewInstr=ddminNew
            ddminNewInstr.mkdir(exist_ok=True)
            runEnv=buildRunEnv(config,parsedCmd,ddmin,instr, ddminNewInstr)

            roundNonDetTab=config.getNonDetTab()
            roundDetTab=config.getDetTab()
            nbRun=config.get_nbRUN()
            if ddmin.name=="NoPerturbation":
                roundNonDetTab=[""]
                nbRun=1
                roundDetTab=[]
            runEnvSav=copy.deepcopy(runEnv)
            for rounding in roundNonDetTab:
                newNbRun=nbRun
                if rounding.startswith("vprec"):
                    newNbRun=1
                if rounding=="":
                    ddminNewRep=ddminNewInstr / "default"
                    if ddmin.name=="ref":
                        ddminNewRep=ddminNewInstr / "nearest"
                        runEnv=rounding_tool.roundingToEnvVar("nearest",runEnvSav)
                        newNbRun=1
                else:
                    ddminNewRep=ddminNewInstr / rounding
                    runEnv=rounding_tool.roundingToEnvVar(rounding,runEnvSav)

                ddminNewRep.mkdir(exist_ok=True)

                runOneConfig(config, refDir, ddminNewRep, runEnv, newNbRun, traceFile)

            if len(roundDetTab)!=0:
                ddminNewRep=ddminNewInstr / "det"
                ddminNewRep.mkdir(exist_ok=True)

                for det in roundDetTab:
                    runEnv=rounding_tool.roundingToEnvVar(det,runEnvSav)
                    if instr!="":
                        runEnv["VERROU_INSTR"]=instr

                    if config.get_count_denorm():
                        if rounding_tool.isRoundingCompatibleWithDenorm(det):
                            runEnv["VERROU_COUNT_DENORM"]="yes"

                    detRep=ddminNewRep/ det
                    detRep.mkdir(exist_ok=True)
                    runOneConfig(config, refDir, detRep, runEnv, 1, traceFile)

def sortSubRep(subRepTab):
    refTab=[x for x in subRepTab if x.name in ["ref","NoPerturbation"] ]
    ddminTab=[x for x in subRepTab if (x.name).startswith("ddmin")]
    otherTab=[x for x in subRepTab if (not x.name in refTab) and (not x in ddminTab)]

    ddminWithKeySort=[]
    for ddmin in ddminTab:
        try:
            xi=int((ddmin.name).replace("ddmin",""))
            ddminWithKeySort+=[(ddmin, xi)]
        except:
            otherTab+=ddmin

    ddminTab=[ddmin[0] for ddmin in sorted(ddminWithKeySort, key=lambda x:x[1])]
    res=sorted(refTab) + ddminTab + sorted(otherTab)

    return res

#warning copy past from verrou_dd_back
def disable_ASLR():
    import ctypes
    import ctypes.util
    # We call personality(ADDR_NO_RANDOMIZE) to disable ASLR, so that addresses during reference run
    # always match addresses during sample runs (even for .so code).
    ADDR_NO_RANDOMIZE = 0x0040000
    libc_name = ctypes.util.find_library("c")
    libc = ctypes.CDLL(libc_name)
    personality = libc.personality
    personality(ADDR_NO_RANDOMIZE)

if __name__=="__main__":
    disable_ASLR()
    config=post_config.postConfig(sys.argv,os.environ)

    repSubRep=config.get_rep_sub_rep()
    print("selected sub_rep to postreat:")
    for rep in sorted(repSubRep.keys()):
        ddMinList=sortSubRep(repSubRep[rep])
        for ddmin in ddMinList:
            print("\t", ddmin.relative_to(Path.cwd()) )
    for rep in sorted(repSubRep.keys()):
        ddMinList=sortSubRep(repSubRep[rep])
        refDir=(rep / "ref").absolute()
        runSubRepForOneInstr(config, rep, refDir, ddMinList)

        #insert Analyse
        estimatorTab=["dc","wdc","wdc-stol","fdr-stol", "data"]

        clean=config.get_trace_clean_intermediate()
        generateTraceAnalysis(rep, config.get_trace_type() , estimatorTab, clean)
