#!/usr/bin/env python3

from traceAnalysis import generateTraceAnalysis,detect_trace_kind
from pathlib import Path
import sys

if __name__=="__main__":
    baseRep=Path(".")
    if len(sys.argv)==2:
        baseRep=Path(sys.argv[1])

    trace_kind=detect_trace_kind(baseRep)
    estimatorTab=["dc","wdc","wdc-stol","fdr-stol", "data"]
    clean=False

    generateTraceAnalysis(baseRep, trace_kind, estimatorTab, clean)
