#!/usr/bin/env python3
# This file is part of Verrou, a FPU instrumentation tool.

# Copyright (C) 2014-2021 EDF
#   F. Févotte <francois.fevotte@edf.fr>
#   B. Lathuilière <bruno.lathuiliere@edf.fr>


# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public License as
# published by the Free Software Foundation; either version 2.1 of the
# License, or (at your option) any later version.

# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.

# You should have received a copy of the GNU Lesser General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
# 02111-1307, USA.

# The GNU Lesser General Public License is contained in the file COPYING.


import sys
import os
from valgrind import dd_config
from valgrind import DD_stoch
from valgrind import DD_exec_stat


class DDsym(DD_stoch.DDStoch):
    def __init__(self, config, prefix="dd.sym"):
        DD_stoch.DDStoch.__init__(self, config, prefix)

    def referenceRunEnv(self):
        return {"VERROU_ROUNDING_MODE": "nearest",
                         "VERROU_MCA_MODE": "ieee",
                         "VERROU_GEN_EXCLUDE":   os.path.join(self.ref_,"dd.sym.%p")}

    def isFileValidToMerge(self, name):
        return name.startswith("dd.sym.")

    def getDeltaFileName(self):
        return "dd.sym"

    def sampleRunEnv(self,dirName):
        return {"VERROU_EXCLUDE": os.path.join(dirName, self.getDeltaFileName() +".exclude")}

    def coerce(self, delta_config):
        return "\n  " + "\n  ".join(delta_config)








if __name__ == "__main__":
    et=DD_exec_stat.exec_stat("dd.sym")
    config=dd_config.ddConfig(sys.argv,os.environ, ["INTERFLOP","VERROU"])
    dd = DDsym(config)
    dd.run()
    et.terminate()
