Verrou, Check floating-point rounding errors
Copyright (C) 2014-2016, F. Fevotte & B. Lathuiliere.

First seed : XXX
Backend verrou : test-version
Backend mcaquad : test-version
Backend checkcancellation : test-version
Backend checkdenorm : test-version
Instrumented operations :
	add : yes
	sub : yes
	mul : yes
	div : yes
	mAdd : yes
	mSub : yes
	cmp : no
	conv : yes
	max : no
	min : no
Instrumented scalar operations : no
Backend verrou simulating UPWARD rounding mode

 ---------------------------------------------------------------------
 Operation                            Instruction count
  `- Precision
      `- Vectorization          Total             Instrumented
 ---------------------------------------------------------------------
 add                     3000                     1000          ( 33%)
  `- flt                     3000                     1000      ( 33%)
      `- llo                     3000                     1000  ( 33%)
 ---------------------------------------------------------------------
 sub                        3                        1          ( 33%)
  `- flt                        3                        1      ( 33%)
      `- llo                        3                        1  ( 33%)
 ---------------------------------------------------------------------
ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
