Verrou, Check floating-point rounding errors
Copyright (C) 2014-2016, F. Fevotte & B. Lathuiliere.

Simulating NEAREST rounding mode
Instrumented operations :
	add : yes
	sub : yes
	mul : yes
	div : yes
	mAdd : yes
	mSub : yes
	cmp : no
	conv : no
	max : no
	min : no
Instrumented scalar operations : no

 ---------------------------------------------------------------------
 Operation                            Instruction count
  `- Precision
      `- Vectorization          Total             Instrumented
 ---------------------------------------------------------------------
 add                      300                      200          ( 67%)
  `- flt                      300                      200      ( 67%)
      `- llo                      300                      200  ( 67%)
 ---------------------------------------------------------------------
 cmp                        6                        0          (  0%)
  `- dbl                        6                        0      (  0%)
      `- scal                       6                        0  (  0%)
 ---------------------------------------------------------------------
 conv                     312                        0          (  0%)
  `- dbl=>flt                 300                        0      (  0%)
      `- scal                     300                        0  (  0%)
  `- flt=>dbl                  12                        0      (  0%)
      `- scal                      12                        0  (  0%)
 ---------------------------------------------------------------------
ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
