Verrou, Check floating-point rounding errors
Copyright (C) XXXXX 

First seed : XXX
Backend verrou : test-version
Backend checkcancellation : test-version
Backend check_float_max : test-version
Backend checkdenorm : test-version
Instrumented operations :
	add : yes
	sub : yes
	mul : yes
	div : yes
	mAdd : yes
	mSub : yes
	sqrt : yes
	cmp : no
	conv : yes
	max : no
	min : no
Instrumented vectorized operations :
	scal : no
	llo  : yes
	vec2  : yes
	vec4  : yes
	vec8  : yes
	unk  : yes
Instrumented type :
	flt : yes
	dbl : yes
EXCLUDE DETECTED: XXXXX
EXCLUDE DETECTED: XXXXX
Using exclusion rule: *	XXXXX
Using exclusion rule: *	XXXXX
Denorm Output:  (mul dbl)
   at 0xFFFFFF: main (denorm.cxx:23)

Denorm Output:  (mul flt)
   at 0xFFFFFF: main (denorm.cxx:25)

Denorm Input:  (mAdd dbl 2)
   at 0xFFFFFF: double vr_fma<double>(double const&, double const&, double const&) (fmaintrin.h:73)
   by 0xFFFFFF: main (denorm.cxx:28)

Denorm Output:  (mAdd dbl)
   at 0xFFFFFF: double vr_fma<double>(double const&, double const&, double const&) (fmaintrin.h:73)
   by 0xFFFFFF: main (denorm.cxx:28)

Denorm Input:  (mul dbl 1)
   at 0xFFFFFF: main (denorm.cxx:37)


 ---------------------------------------------------------------------
 Operation                            Instruction count
  `- Precision
      `- Vectorization          Total             Instrumented
 ---------------------------------------------------------------------
 add                        1                        1          (100%)
  `- dbl                        1                        1      (100%)
      `- llo                        1                        1  (100%)
 ---------------------------------------------------------------------
 mul                        3                        3          (100%)
  `- flt                        1                        1      (100%)
      `- llo                        1                        1  (100%)
  `- dbl                        2                        2      (100%)
      `- llo                        2                        2  (100%)
 ---------------------------------------------------------------------
 mAdd                       1                        1          (100%)
  `- dbl                        1                        1      (100%)
 ---------------------------------------------------------------------
ERROR SUMMARY: 6 errors from 5 contexts (suppressed: 0 from 0)
