Verrou, Check floating-point rounding errors
Copyright (C) 2014-2016, F. Fevotte & B. Lathuiliere.

First seed : XXX
Backend verrou : test-version
Backend mcaquad : test-version
Backend checkcancellation : test-version
Backend checkdenorm : test-version
Instrumented operations :
	add : yes
	sub : yes
	mul : yes
	div : yes
	mAdd : yes
	mSub : yes
	cmp : no
	conv : yes
	max : no
	min : no
Instrumented scalar operations : no

 ---------------------------------------------------------------------
 Operation                            Instruction count
  `- Precision
      `- Vectorization          Total             Instrumented
 ---------------------------------------------------------------------
 mul                        2                        2          (100%)
  `- flt                        1                        1      (100%)
      `- llo                        1                        1  (100%)
  `- dbl                        1                        1      (100%)
      `- llo                        1                        1  (100%)
 ---------------------------------------------------------------------
 mAdd                       1                        1          (100%)
  `- dbl                        1                        1      (100%)
      `- llo                        1                        1  (100%)
 ---------------------------------------------------------------------
ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
