Verrou, Check floating-point rounding errors
Copyright (C) XXXXX 

First seed : XXX
Backend verrou : test-version
Backend checkcancellation : test-version
Backend check_float_max : test-version
Backend checkdenorm : test-version
Instrumented operations :
	add : yes
	sub : yes
	mul : yes
	div : yes
	mAdd : yes
	mSub : yes
	sqrt : yes
	cmp : no
	conv : yes
	max : no
	min : no
Instrumented vectorized operations :
	scal : no
	llo  : yes
	vec2  : yes
	vec4  : yes
	vec8  : yes
	unk  : yes
Instrumented type :
	flt : yes
	dbl : yes
Backend verrou simulating FLOAT rounding mode
EXCLUDE DETECTED: XXXXX
Using exclusion rule: *	XXXXX

 ---------------------------------------------------------------------
 Operation                            Instruction count
  `- Precision
      `- Vectorization          Total             Instrumented
 ---------------------------------------------------------------------
 add                    12000                     4000          ( 33%)
  `- flt                     1000                        0      (  0%)
      `- llo                     1000                        0  (  0%)
  `- dbl                    11000                     4000      ( 36%)
      `- llo                    11000                     4000  ( 36%)
 ---------------------------------------------------------------------
 sub                       32                       12          ( 37%)
  `- flt                        1                        0      (  0%)
      `- llo                        1                        0  (  0%)
  `- dbl                       31                       12      ( 39%)
      `- llo                       31                       12  ( 39%)
 ---------------------------------------------------------------------
ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
