Verrou, Check floating-point rounding errors
Copyright (C) XXXXX 

First seed : XXX
Backend verrou : test-version
Backend checkcancellation : test-version
Backend check_float_max : test-version
Backend checkdenorm : test-version
Instrumented operations :
	add : yes
	sub : yes
	mul : yes
	div : yes
	mAdd : yes
	mSub : yes
	sqrt : yes
	cmp : no
	conv : yes
	max : no
	min : no
Instrumented vectorized operations :
	scal : no
	llo  : yes
	vec2  : yes
	vec4  : yes
	vec8  : yes
	unk  : yes
Instrumented type :
	flt : yes
	dbl : yes
Backend verrou simulating NEAREST rounding mode
EXCLUDE DETECTED: XXXXX
Using exclusion rule: *	XXXXX
Cancellation: 
   at 0xFFFFFF: compute (hardSoftClreq.c:14)
   by 0xFFFFFF: main (hardSoftClreq.c:41)

Cancellation: 
   at 0xFFFFFF: detect (hardSoftClreq.c:19)
   by 0xFFFFFF: main (hardSoftClreq.c:42)

Cancellation: 
   at 0xFFFFFF: compute (hardSoftClreq.c:14)
   by 0xFFFFFF: main (hardSoftClreq.c:47)

Cancellation: 
   at 0xFFFFFF: detect (hardSoftClreq.c:19)
   by 0xFFFFFF: main (hardSoftClreq.c:48)

Cancellation: 
   at 0xFFFFFF: compute (hardSoftClreq.c:14)
   by 0xFFFFFF: main (hardSoftClreq.c:59)

Cancellation: 
   at 0xFFFFFF: detect (hardSoftClreq.c:19)
   by 0xFFFFFF: main (hardSoftClreq.c:60)

Cancellation: 
   at 0xFFFFFF: compute (hardSoftClreq.c:14)
   by 0xFFFFFF: main (hardSoftClreq.c:62)

Cancellation: 
   at 0xFFFFFF: detect (hardSoftClreq.c:19)
   by 0xFFFFFF: main (hardSoftClreq.c:63)


 ---------------------------------------------------------------------
 Operation                            Instruction count
  `- Precision
      `- Vectorization          Total             Instrumented
 ---------------------------------------------------------------------
 add                    11000                     4000          ( 36%)
  `- flt                    11000                     4000      ( 36%)
      `- llo                    11000                     4000  ( 36%)
 ---------------------------------------------------------------------
 sub                       21                        8          ( 38%)
  `- flt                       21                        8      ( 38%)
      `- llo                       21                        8  ( 38%)
 ---------------------------------------------------------------------
ERROR SUMMARY: 8 errors from 8 contexts (suppressed: 0 from 0)
