Verrou, Check floating-point rounding errors
Copyright (C) XXXXX 

First seed : XXX
Backend verrou : test-version
Backend checkcancellation : test-version
Backend check_float_max : test-version
Backend checkdenorm : test-version
Instrumented operations :
	add : yes
	sub : yes
	mul : yes
	div : yes
	mAdd : yes
	mSub : yes
	sqrt : yes
	cmp : no
	conv : yes
	max : no
	min : no
Instrumented vectorized operations :
	scal : no
	llo  : yes
	vec2  : yes
	vec4  : yes
	vec8  : yes
	unk  : yes
Instrumented type :
	flt : yes
	dbl : yes
Frontend: double -> float
Backend verrou simulating UPWARD rounding mode
EXCLUDE DETECTED: XXXXX
Using exclusion rule: *	XXXXX

 ---------------------------------------------------------------------
 Operation                            Instruction count
  `- Precision
      `- Vectorization          Total             Instrumented
 ---------------------------------------------------------------------
 add                    12000                     6000          ( 50%)
  `- flt                     1000                     1000      (100%)
      `- llo                     1000                     1000  (100%)
  `- dbl                    11000                     5000      ( 45%)
      `- llo                    11000                     5000  ( 45%)
 ---------------------------------------------------------------------
 sub                       32                       14          ( 44%)
  `- flt                        1                        1      (100%)
      `- llo                        1                        1  (100%)
  `- dbl                       31                       13      ( 42%)
      `- llo                       31                       13  ( 42%)
 ---------------------------------------------------------------------
ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
