Verrou, Check floating-point rounding errors
Copyright (C) XXXXX 

First seed : XXX
Backend verrou : test-version
Backend mcaquad : test-version
Backend checkcancellation : test-version
Backend check_float_max : test-version
Backend checkdenorm : test-version
Instrumented operations :
	add : yes
	sub : yes
	mul : yes
	div : yes
	mAdd : yes
	mSub : yes
	sqrt : yes
	cmp : no
	conv : yes
	max : no
	min : no
Instrumented vectorized operations :
	scal : no
	llo  : yes
	vec2  : yes
	vec4  : yes
	vec8  : yes
	unk  : yes
Instrumented type :
	flt : yes
	dbl : yes
	ldbl : no
Backend verrou simulating RANDOM rounding mode
EXCLUDE DETECTED: XXXXX
EXCLUDE DETECTED: XXXXX
EXCLUDE DETECTED: XXXXX
EXCLUDE DETECTED: XXXXX
Using exclusion rule: *	XXXXX
Using exclusion rule: *	XXXXX
Using exclusion rule: *	XXXXX
Using exclusion rule: *	XXXXX
Interlibm counter ( ROUNDINGMODE=RANDOM )
		 Total 	Instrumented
---------------------------------------------------
cos		240	160
 `- flt 	120	80
 `- dbl 	120	80
---------------------------------------------------
atan2		240	160
 `- flt 	120	80
 `- dbl 	120	80

 ---------------------------------------------------------------------
 Operation                            Instruction count
  `- Precision
      `- Vectorization          Total             Instrumented
 ---------------------------------------------------------------------
 add                    32920                        0          (  0%)
  `- flt                      280                        0      (  0%)
      `- llo                      280                        0  (  0%)
  `- dbl                    32640                        0      (  0%)
      `- llo                    32640                        0  (  0%)
 ---------------------------------------------------------------------
 sub                     9000                      160          (  2%)
  `- flt                      440                       80      ( 18%)
      `- llo                      440                       80  ( 18%)
  `- dbl                     8560                       80      (  1%)
      `- llo                     8560                       80  (  1%)
 ---------------------------------------------------------------------
 mul                    31281                        0          (  0%)
  `- flt                      560                        0      (  0%)
      `- llo                      560                        0  (  0%)
  `- dbl                    30721                        0      (  0%)
      `- llo                    30721                        0  (  0%)
 ---------------------------------------------------------------------
 div                    18080                        0          (  0%)
  `- flt                    18000                        0      (  0%)
      `- llo                    18000                        0  (  0%)
  `- dbl                       80                        0      (  0%)
      `- llo                       80                        0  (  0%)
 ---------------------------------------------------------------------
 mAdd                    1160                        0          (  0%)
  `- dbl                     1160                        0      (  0%)
 ---------------------------------------------------------------------
ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
