Verrou, Check floating-point rounding errors
Copyright (C) XXXXX 

First seed : XXX
Backend verrou : test-version
Backend mcaquad : test-version
Backend checkcancellation : test-version
Backend check_float_max : test-version
Backend checkdenorm : test-version
Instrumented operations :
	add : yes
	sub : yes
	mul : yes
	div : yes
	mAdd : yes
	mSub : yes
	cmp : no
	conv : yes
	max : no
	min : no
Instrumented vectorized operations :
	scal : no
	llo  : yes
	vec2  : yes
	vec4  : yes
	vec8  : yes
	unk  : yes
Instrumented type :
	flt : yes
	dbl : yes
Backend verrou simulating RANDOM rounding mode
NaN: 
   at 0xFFFFFF: main (naninf.cxx:34)

NaN: 
   at 0xFFFFFF: main (naninf.cxx:35)

NaN: 
   at 0xFFFFFF: main (naninf.cxx:36)

NaN: 
   at 0xFFFFFF: main (naninf.cxx:37)

NaN: 
   at 0xFFFFFF: main (naninf.cxx:38)

NaN: 
   at 0xFFFFFF: main (naninf.cxx:48)

NaN: 
   at 0xFFFFFF: main (naninf.cxx:49)

NaN: 
   at 0xFFFFFF: main (naninf.cxx:50)

NaN: 
   at 0xFFFFFF: main (naninf.cxx:51)


 ---------------------------------------------------------------------
 Operation                            Instruction count
  `- Precision
      `- Vectorization          Total             Instrumented
 ---------------------------------------------------------------------
 add                        8                        8          (100%)
  `- dbl                        8                        8      (100%)
      `- llo                        8                        8  (100%)
 ---------------------------------------------------------------------
 sub                        2                        2          (100%)
  `- dbl                        2                        2      (100%)
      `- llo                        2                        2  (100%)
 ---------------------------------------------------------------------
 div                        3                        3          (100%)
  `- dbl                        3                        3      (100%)
      `- llo                        3                        3  (100%)
 ---------------------------------------------------------------------
ERROR SUMMARY: 9 errors from 9 contexts (suppressed: 0 from 0)
