Verrou, Check floating-point rounding errors
Copyright (C) 2014-2016, F. Fevotte & B. Lathuiliere.

First seed : 42
Backend verrou : test-version
Backend mcaquad : test-version
Backend checkcancellation : test-version
Backend checkdenorm : test-version
Instrumented operations :
	add : yes
	sub : yes
	mul : yes
	div : yes
	mAdd : yes
	mSub : yes
	cmp : no
	conv : yes
	max : no
	min : no
Instrumented scalar operations : no
Backend verrou simulating RANDOM rounding mode

 ---------------------------------------------------------------------
 Operation                            Instruction count
  `- Precision
      `- Vectorization          Total             Instrumented
 ---------------------------------------------------------------------
 add                   100001                   100000          (100%)
  `- flt                   100001                   100000      (100%)
      `- llo                   100001                   100000  (100%)
 ---------------------------------------------------------------------
 mul                        1                        0          (  0%)
  `- flt                        1                        0      (  0%)
      `- llo                        1                        0  (  0%)
 ---------------------------------------------------------------------
ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
