Verrou, Check floating-point rounding errors
Copyright (C) 2014, F. Fevotte & B. Lathuiliere.

Simulating NEAREST rounding mode
Client Request: instrumentation switched ON
Client Request: instrumentation switched OFF

    ------------------------------------
    Operation
     `- Precision
         `- Vectorization          Count
    ------------------------------------
    add                   100000
     `- flt                   100000
         `- llo                   100000
    ------------------------------------
