Verrou, Check floating-point rounding errors
Copyright (C) 2014, F. Fevotte & B. Lathuiliere.

Simulating RANDOM rounding mode
Instrumented operations :
	add : yes
	sub : yes
	mul : yes
	div : yes
	mAdd : yes
	mSub : yes
Instrumented scalar operations : no

 ---------------------------------------------------------------------
 Operation                            Instruction count
  `- Precision
      `- Vectorization          Total             Instrumented
 ---------------------------------------------------------------------
 add                   100001                   100000          (100%)
  `- flt                   100001                   100000      (100%)
      `- llo                   100001                   100000  (100%)
 ---------------------------------------------------------------------
 sub                        1                        0          (  0%)
  `- flt                        1                        0      (  0%)
      `- llo                        1                        0  (  0%)
 ---------------------------------------------------------------------
 mul                        2                        0          (  0%)
  `- flt                        2                        0      (  0%)
      `- llo                        2                        0  (  0%)
 ---------------------------------------------------------------------
