Verrou, Check floating-point rounding errors
Copyright (C) XXXXX 

First seed : XXX
Backend verrou : test-version
Backend mcaquad : test-version
Backend checkcancellation : test-version
Backend check_float_max : test-version
Backend checkdenorm : test-version
Instrumented operations :
	add : yes
	sub : yes
	mul : yes
	div : yes
	mAdd : yes
	mSub : yes
	cmp : no
	conv : yes
	max : no
	min : no
Instrumented vectorized operations :
	scal : no
	llo  : yes
	vec2  : yes
	vec4  : yes
	vec8  : yes
	unk  : yes
Instrumented type :
	flt : yes
	dbl : yes
Backend verrou simulating RANDOM rounding mode

 ---------------------------------------------------------------------
 Operation                            Instruction count
  `- Precision
      `- Vectorization          Total             Instrumented
 ---------------------------------------------------------------------
 add                   100001                   100000          (100%)
  `- flt                   100001                   100000      (100%)
      `- llo                   100001                   100000  (100%)
 ---------------------------------------------------------------------
 sub                        1                        0          (  0%)
  `- flt                        1                        0      (  0%)
      `- llo                        1                        0  (  0%)
 ---------------------------------------------------------------------
 mul                        2                        0          (  0%)
  `- flt                        2                        0      (  0%)
      `- llo                        2                        0  (  0%)
 ---------------------------------------------------------------------
 cmp                        1                        0          (  0%)
  `- dbl                        1                        0      (  0%)
      `- scal                       1                        0  (  0%)
 ---------------------------------------------------------------------
 conv                       4                        0          (  0%)
  `- dbl=>flt                   2                        0      (  0%)
  `- flt=>dbl                   2                        0      (  0%)
 ---------------------------------------------------------------------
ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
