Verrou, Check floating-point rounding errors
Copyright (C) XXXXX 

First seed : XXX
Backend verrou : test-version
Backend checkcancellation : test-version
Backend check_float_max : test-version
Backend checkdenorm : test-version
Instrumented operations :
	add : yes
	sub : yes
	mul : yes
	div : yes
	mAdd : yes
	mSub : yes
	sqrt : yes
	cmp : no
	conv : yes
	max : no
	min : no
Instrumented vectorized operations :
	scal : no
	llo  : yes
	vec2  : yes
	vec4  : yes
	vec8  : yes
	unk  : yes
Instrumented type :
	flt : yes
	dbl : yes
Frontend: unfused
Backend verrou simulating NEAREST rounding mode
EXCLUDE DETECTED: XXXXX
EXCLUDE DETECTED: XXXXX
Using exclusion rule: *	XXXXX
Using exclusion rule: *	XXXXX

 ---------------------------------------------------------------------
 Operation                            Instruction count
  `- Precision
      `- Vectorization          Total             Instrumented
 ---------------------------------------------------------------------
 add                       22                        8          ( 36%)
  `- flt                       11                        4      ( 36%)
      `- llo                       11                        4  ( 36%)
  `- dbl                       11                        4      ( 36%)
      `- llo                       11                        4  ( 36%)
 ---------------------------------------------------------------------
 mul                       22                        8          ( 36%)
  `- flt                       11                        4      ( 36%)
      `- llo                       11                        4  ( 36%)
  `- dbl                       11                        4      ( 36%)
      `- llo                       11                        4  ( 36%)
 ---------------------------------------------------------------------
 mAdd                      22                        8          ( 36%)
  `- flt                       11                        4      ( 36%)
  `- dbl                       11                        4      ( 36%)
 ---------------------------------------------------------------------
ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
