#!/bin/bash

TMP=$(mktemp)
trap "{ echo 'cleaning up'; rm -f ${TMP};}" EXIT

while [ ! -z "$1" ]; do
    FILE="$1"
    echo "Fixing encoding of file ${FILE}"
    iconv -f iso-8859-1 -t utf-8 -o ${TMP} ${FILE}
    sed 's/iso-8859-1/utf-8/i' ${TMP} >${FILE}
    shift
done
