#!/usr/bin/env python3

import os
import subprocess
import re
import os.path
import sys

env = os.environ
env["COLUMNS"] = "81"

installConfig= subprocess.Popen(["./config.status", "--config"],
                       env = env,
                       stdout = subprocess.PIPE)

line = (installConfig.stdout.readline()).decode("utf8")
spline=(line.strip()).split()
pathInstall="./install"
for conf in spline:
    if conf[1:-1].startswith("--prefix"):
        pathInstall=(conf[1:-1].partition('='))[2]

manPath=os.path.join(pathInstall, "share/man/man1/valgrind.1")
if not os.path.exists(manPath):
    print("unable to find valgrind man file : "+ manPath)
    sys.exit(42)

man = subprocess.Popen(["man", manPath],
                       env = env,
                       stdout = subprocess.PIPE)


verrouFound=False
for line in man.stdout:
    line=line.decode("utf8")
    if line.startswith("VERROU"):
        verrouFound=True
        break

if not verrouFound:
    print("valgrind man file does not contain VERROU options : "+ manPath)
    sys.exit(42)

title = re.compile("^[A-Z]")
subtitle = re.compile("^\s{3}[A-Z]")

linesRes=[]
for line in man.stdout:
    line=line.decode("utf8")
    if title.search(line):
        break
    if subtitle.search(line):
        line = " " + line
    else:
        line = line[1:]

    line=line.replace('","','\\",\\"')
    linesRes+=[line.rstrip()]

#with open("verrou/vr_clo_gen.c", "w") as f:
#    for line in linesRes:
#        f.write ('VG_(printf)( "'+line+'\\n"'+"    );\n")

with open("verrou/vr_clo.txt", "w") as f:
    f.write('"')
    for line in linesRes[0:-1]:
        f.write (line+'\\n\\'+"\n")
    f.write(linesRes[-1]+'"\n')


