#!/bin/bash

set -e

SRCDIR=$(
    cd "$(dirname "${BASH_SOURCE[0]}")"/../..
    pwd)
echo "SRCDIR=${SRCDIR}"

BUILDDIR="${PWD}"
echo "BUILDDIR=${BUILDDIR}"

INSTALLDIR="${BUILDDIR}/install"
echo "INSTALLDIR=${INSTALLDIR}"

[ -r "${INSTALLDIR}/env.sh" ] || (
    echo "Could not find ${INSTALLDIR}/env.sh"
    false
)

(
    cd ${SRCDIR}/verrou;
    git diff --no-ext-diff --ignore-submodules --quiet --exit-code
) || (
    echo "Please commit your local changes"
    false
)

HASH=$(cd ${SRCDIR}/verrou;
       git rev-parse --short=14 HEAD)
echo "HASH=${HASH}"

echo "Press a key to continue (Ctrl+C to abort)"
read

# Build and install documentation
make -C docs html-docs man-pages
make install
${SRCDIR}/verrou/docs/fix-encoding ${INSTALLDIR}/share/doc/valgrind/html/*.html


# Update usage string in source files
${SRCDIR}/verrou/docs/update-vr-clo

# Upload HTML documentation to github
TMPDIR=$(mktemp -d)
trap "echo -e '\n\nCleaning up...'; rm -rf ${TMPDIR}" EXIT
(
    cd ${TMPDIR}
    git clone --branch gh-pages --single-branch https://github.com/edf-hpc/verrou.git html
    cd html
)
rsync -av --delete --exclude .git ${INSTALLDIR}/share/doc/valgrind/html/ ${TMPDIR}/html/
(
    cd ${TMPDIR}/html
    git add .
    git status
    (
        echo "Updated documentation to ${HASH}"
        echo ""
        echo "REMOVE THIS LINE TO COMMIT THESE CHANGES AND UPLOAD THEM"
    ) >../commit.msg
    (
        echo "echo 'Staged changes'"
        echo "git status --porcelain | grep '^??'"
        echo "git diff --staged --stat"
    ) >../bashrc
    git config user.name  "François Févotte"
    git config user.email "francois.fevotte@triscale-innov.com"
    x-terminal-emulator -e "bash --init-file ../bashrc" &
    firefox --new-window "vr-manual.html" &
    git commit -t ../commit.msg
    git push origin gh-pages
)
