#!/usr/bin/python

import os
import subprocess
import re

env = os.environ
env["COLUMNS"] = "81"
man = subprocess.Popen(["man", "./install/share/man/man1/valgrind.1"],
                       env = env,
                       stdout = subprocess.PIPE)

for line in man.stdout:
    if line.startswith("VERROU"):
        break

title = re.compile("^[A-Z]")
subtitle = re.compile("^\s{3}[A-Z]")
for line in man.stdout:
    if title.search(line):
        break

    if subtitle.search(line):
        line = " " + line
    else:
        line = line[1:]

    print '"'+line.rstrip()+'\\n"'
