#!/usr/bin/env python3

import os
import subprocess
import re
import sys
from pathlib import Path

env = os.environ
env["COLUMNS"] = "81"

installConfig= subprocess.Popen(["./config.status", "--config"],
                       env = env,
                       stdout = subprocess.PIPE)

line = (installConfig.stdout.readline()).decode("utf8").replace("'","")
spline=(line.strip()).split()
pathInstall="./install"
for conf in spline:
    if conf.startswith("--prefix"):
        pathInstall=Path((conf.partition('='))[2])

manPath=pathInstall / "share" / "man" / "man1" / "valgrind.1"
if not manPath.is_file():
    print("unable to find valgrind man file : "+ manPath)
    sys.exit(42)

man = subprocess.Popen(["man", manPath],
                       env = env,
                       stdout = subprocess.PIPE)


verrouFound=False
for line in man.stdout:
    line=line.decode("utf8")
    if line.startswith("VERROU"):
        verrouFound=True
        break

if not verrouFound:
    print("valgrind man file does not contain VERROU options : "+ manPath)
    sys.exit(42)

title = re.compile(r"^[A-Z]")
subtitle = re.compile(r"^\s{3}[A-Z]")

linesRes=[]
for line in man.stdout:
    line=line.decode("utf8")
    if title.search(line):
        break
    if subtitle.search(line):
        line = " " + line
    else:
        line = line[1:]

    line=line.replace('","','\\",\\"')
    line=line.replace("<yes|no>","yes|no")
    linesRes+=[line.rstrip()]

with open("verrou/vr_clo.txt", "w") as f:
    f.write('"')
    for line in linesRes[0:-1]:
        f.write (line+'\\n\\'+"\n")
    f.write(linesRes[-1]+'"\n')


